In [1]:
import tensorflow as tf

In [8]:
t = tf.constant([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]],[[5,5,5],[6,6,6]]])
size = tf.shape(t)
b = tf.slice(t,[1,0,0],[1,1,3])
c = tf.slice(t,[1,0,0],[2,1,2])

with tf.compat.v1.Session() as sess:
    result = sess.run(b)
    result1 = sess.run(c)
    si = sess.run(size)
    print("size of t : ", si)
    print("b = ",result)
    print("c = ",result1)

size of t :  [3 2 3]
b =  [[[3 3 3]]]
c =  [[[3 3]]

 [[5 5]]]


slice(input_, begin, size, name=None):
<p> 上面例子中slice 读取规则
<p> t 张量的尺寸为 3*2*3
<p> 其读取规则为：begin = [1,0,0]，size= [1,1,3],size 与begin 一一对应，begin 1 代表第一个维度的起始位置为[[3,3,3],[4,4,4]]
<p> size 中与之对应的是 1  也就是在第一个维度的层面上去1个，也就是仅仅在[[3,3,3],[4,4,4]]中提取，接下来第二个维度其实位置也是0 ，
<p> 而 size中依然对应1,也就是维度2 中也仅仅取1个，而在第三个维度中 size 为3 也就是取三个，而起始位置是0，因此去取三个就是[3,3,3] 

#### tf.stack
<p>stack(values, axis=0, name='stack') 
<p>Stacks a list of rank-`R` tensors into one rank-`(R+1)` tensor.
<p>Given a list of length `N` of tensors of shape `(A, B, C)`;

<p>if `axis == 0` then the `output` tensor will have the shape `(N, A, B, C)`.
<p>if `axis == 1` then the `output` tensor will have the shape `(A, N, B, C)`.
<p> tf.stack([x, y, z]) = np.stack([x, y, z])

In [13]:
a = tf.constant([[1, 2], [3, 4], [5, 6]])
s = tf.shape(a)
a1 = tf.tile(a, [2, 3])
with tf.compat.v1.Session() as sess:
    R = sess.run(a1)
    s_a = sess.run(s)
    print(s_a)
    print(R)
    

[3 2]
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [5 6 5 6 5 6]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [5 6 5 6 5 6]]
